package com.freelauncer.model;

import lombok.Data;

import javax.persistence.*;

/**
 * SPaymentFee generated by hbm2java
 */
@Entity
@Data
@Table(name = "sima_domain_blacklist")
public class DomainBlackList implements java.io.Serializable {

    @Id
//    @SequenceGenerator(name = "SIMA_SHOP_MANAGER_SEQ", sequenceName = "SIMA_SHOP_MANAGER_SEQ", allocationSize = 1)
//    @GeneratedValue(strategy = GenerationType.SEQUENCE, generator = "SIMA_SHOP_MANAGER_SEQ")
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    @Column(name = "ID", unique = true, nullable = false, precision = 22, scale = 0)
    private Long id;

    @Column(name = "NAME", length = 100)
    private String name;

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getName() {
        return name;
    }

    public void setName(String name) {
        this.name = name;
    }

}
